### ISSUE TITLE
Issue with pathwayEnrichment()

### ISSUE THREAD

**Issue by Navin-tamil** [hancockinformatics/pathnet#17]
library(DESeq2)
a<-load("/home/Downloads/exampleDESeqResults.rda")   #######Downloaded the dataset from your github
str(a)
head(as.data.frame(exampleDESeqResults)) 
pathway_results <- pathwayEnrichment(inputList = list(as.data.frame(exampleDESeqResults)),columnFC = "COVID.Pos.Over.Time.log2FoldChange", columnP = "COVID.Neg.Over.Time.padj", 
                                     filterInput = TRUE, split=TRUE, analysis="hallmark", filterResults="default")

![Screenshot from 2024-09-26 12-39-43](https://github.com/user-attachments/assets/f47fa0e8-17c8-4671-94f4-ba87b33f3cc4)

Would like to know why is the error coming when I am using your dataset. Is it the error due input format I am giving or parsing error within the function.

**Comment by travis-m-blimkie** [comment]
Hello,

For the example data, you don't need wrap to it in the `list(as.data.frame(...))` part - its already formatted in the way `pathwayEnrichment` expects. And you can load the example data directly from the package, without having to download it. The following works for me:

```r
library(pathlinkR)

data("exampleDESeqResults")

pathway_results <- pathwayEnrichment(
  inputList = exampleDESeqResults,
  filterInput = TRUE,
  split = TRUE,
  analysis = "hallmark",
  filterResults = "default"
)
```

Please let me know if this works for you, and I'll close the issue. Or let me know if you have any further questions.

Cheers!

**Comment by Navin-tamil** [comment]
Yes when I am giving it as the same input its working. How to convert my deseq results as the same. Becasue when I onvert it into dataframe I am getting the same error as above. If I input the results directly it is not recogonising the log2Foldchange and padj columns


The deseq results looks as follows when I am printing
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
log2 fold change (MLE): condition Treatment vs Control 
Wald test p-value: condition Treatment vs Control 
DataFrame with ----- rows and 6 columns
                      baseMean log2FoldChange     lfcSE      stat      pvalue
                     <numeric>      <numeric> <numeric> <numeric>   <numeric>
ENS54829     2.21340        4.05272  1.098015   3.69095 2.23414e-04
ENS01753    20.16135       -1.95545  0.493859  -3.95953 7.50960e-05
ENS05540     1.52212        1.79696  0.732622   2.45278 1.41756e-02
ENS11528    70.87050       -1.82843  0.174771 -10.46184 1.29315e-25
ENS54497     8.25096        1.76202  0.489715   3.59805 3.20618e-04
...                        ...            ...       ...       ...         ...
ENS51689    17.25738        1.35550  0.414544   3.26985 1.07603e-03
ENS50667    12.06454       -1.25809  0.498534  -2.52358 1.16166e-02
ENS54081  1110.53736        2.40544  0.272889   8.81474 1.19968e-18
ENS49569 67070.70550        4.41228  0.645868   6.83155 8.40015e-12
ENS53966     7.93544       -1.23945  0.513788  -2.41239 1.58485e-02
                          padj
                     <numeric>
ENS54829 5.30528e-04
ENS01753 1.92816e-04
ENS05540 2.44696e-02
ENS11528 9.17782e-24
ENS54497 7.42427e-04
...                        ...
ENS51689 2.28129e-03
ENS50667 2.03931e-02
ENS54081 2.53108e-17
ENS49569 6.32086e-11
ENS53966 2.70772e-02



Please help me out to fix this

**Comment by travis-m-blimkie** [comment]
If you're results are of class "DESeqResults" then you should only need to wrap them into a named list, something like: `list("treatment_vs_Control" = my_deseq_results)`. 
Or if that doesn't work, then try the following: 
```r
pathwayEnrichment(
  inputList = list("treatment_vs_control" = as.data.frame(my_deseq_results)),
  columnFC = "log2FoldChange",
  columnP = "padj",
  filterInput = TRUE,
  split = TRUE,
  analysis = "hallmark",
  filterResults = "default"
)
```

I also noticed that the gene names in the data you showed don't appear to be standard Ensembl IDs - unfortunately these are required for the  `pathwayEnrichment()` function, so you'll need to map them to standard Ensembl gene IDs first. You can check the help page or vignette for more details on the input requirements.

Cheers!

**Comment by Navin-tamil** [comment]
My results are from cattle and the GeneID too. As it is a public forum I just replaced the species tag and renamed the last two characters of GeneID. Is there options to use species specific enrichment.

**Comment by travis-m-blimkie** [comment]
Unfortunately no, pathlinkR currently only supports human data. You could map your cattle gene IDs to human, set those as the rownames of your input dataframe, and then input that to `pathwayEnrichment()`. There are a number of ways to map gene IDs between species, such as  [biomaRt](https://bioconductor.org/packages/release/bioc/html/biomaRt.html).

**Comment by travis-m-blimkie** [comment]
Closing this issue after one week of inactivity.
