### ISSUE TITLE
Questions about species information

### ISSUE THREAD

**Issue by 146107576** [hancockinformatics/pathnet#19]
Hello, I would like to know if this R package can only analyze the genes of humans? Can genes from other species, such as mice, rats, and rabbits, be used with this pack?

**Comment by travis-m-blimkie** [comment]
At this time we only support human data. You could however use another package such as [biomaRt](https://bioconductor.org/packages/biomaRt/) to translate your mouse/rat/rabbit/etc. genes to human.

**Comment by 146107576** [comment]
Hello, I have another problem. When I am analyzing “Generating networks from enriched pathways”, I find that the pathway names in the long box are not displayed completely, is there a parameter to adjust this? Thank you for your help.

**Comment by travis-m-blimkie** [comment]
Currently no, there's no way to adjust how much of the pathway names are displayed before they're truncated. But I'll make a note to have this parameter added as a function argument in the next release of pathlinkR. 

If you're currently using `pathnetGGraph()`, you could also try `pathnetVisNetwork()` which creates an interative visualization where hovering over a node with your cursor displays the full pathway name.

**Comment by 146107576** [comment]
All right, I got it. Thank you.

**Comment by travis-m-blimkie** [comment]
I had time to implement this change in the development version of pathlinkR, which you can install from either Github or Bioconductor:

```r
# Github development
devtools::install_github("https://github.com/hancockinformatics/pathlinkR")

# Bioconductor develelopment
BiocManager::install("pathlinkR", version="devel")
```

See the argument "nodeLabelLength" in `pathnetGGraph()` and `pathnetVisNetwork()`, and "nodeLabelWrap" in `pathnetGGraph()` to tweak the appearance of the node labels.

Cheers!

**Comment by 146107576** [comment]
Both parameters you provided are valid and your help is much appreciated. Hopefully this tool will be discovered and used by more and more people in the future.
Cheers!
